pipeline {
    agent any

    stages {

        stage('unit Tests') {
            when {
                branch 'dev'
            }
            steps { 
                dir('javaapp-pipeline') {
                    sh 'mvn clean test'
                }
            }
        }
        stage('Build') {
            when {
                branch 'master'
            }
            steps {
                dir('javaapp-pipeline') {
                    sh 'mvn clean package'
                }
            }
        }
            stage('Deploy') {
            when {
                branch 'master'
            }
                steps{
                    dir('javaapp-pipeline/target') {
                        sh '''
                        if pgrep -f "java -jar java-sample-21-1.0.0.jar" > /dev/null; then
                            pkill -f "java -jar java-sample-21-1.0.0.jar"
                            echo "App was running and has been killed."
                        else
                            echo "App is not running."
                        fi
                        JENKINS_NODE_COOKIE=dontKillMe nohup java -jar java-sample-21-1.0.0.jar > app.log 2>&1 &
                    '''
                    }
                }
            }
        }
    }
    
                
